name: GitHub Pages Release

on:
  push:
    branches:
      - master

  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
          # cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
          # cache-path: ${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:
          # architecture: x64
      - run: flutter pub get
      - run: flutter test
      # - name: Clone Flutter repository with master channel
      #   uses: subosito/flutter-action@48cafc24713cca54bbe03cdc3a423187d413aafa
      #   with:
      #     channel: master
      # - run: flutter doctor -v

      # - name: Install web dependencies
      #   uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c
      #   with:
      #     node-version: "14"
      # - run: npm install -g firebase-tools@11.0.1

      # # Checkout gallery code and get packages.
      # - name: Checkout gallery code
      #   uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      # - run: flutter pub get

      # - uses: actions/checkout@v3

      # - name: Setup Flutter
      #   run: |
      #     git clone https://github.com/flutter/flutter.git --depth 1 -b beta _flutter
      #     echo "${GITHUB_WORKSPACE}/_flutter/bin" >> ${GITHUB_PATH}
  
      # - name: Install
      #   run: |
      #     flutter config --enable-web
      #     flutter pub get
  
      - name: Build
        run: flutter build web --release
  
      - name: Deploy to Github pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./build/web
      - name: 'Deploy to Netlify'
        uses: jsmrcaga/action-netlify-deploy@v2.0.0
        with:
          NETLIFY_AUTH_TOKEN: Ur7kJI_2L5DGzXh7BrcBHT8f9RQAfCKzBwoIuoSDL_c
          NETLIFY_SITE_ID: 0b38f025-452f-4bb3-a1a6-a5137530f814
          NETLIFY_DEPLOY_MESSAGE: "Prod deploy v${{ github.ref }}"
          NETLIFY_DEPLOY_TO_PROD: true
          install_command: "echo Skipping installing the dependencies"
          build_command: "echo Skipping building the web files"


# jobs:
#   build:
#     name: Create Web Build
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - uses: actions/setup-java@v3
#         with:
#           distribution: 'zulu'
#           java-version: "12.x"
#           cache: gradle
#       - uses: subosito/flutter-action@v2
#         with:
#           flutter-version: "3.0.0"
#           channel: 'stable'
#           cache: true
      
#       - name: Get dependencies
#         run: flutter pub get

#       - name: Start Web Release Build
#         run: flutter build web --release
     
#       - name: Upload Web Build Files
#         uses: actions/upload-artifact@v2
#         with:
#           name: web-release
#           path: ./build/web

#   deploy:
#     name: Deploy Web Build
#     needs: build
#     runs-on: ubuntu-latest

#     steps:
#     - name: Download Web Release
#       uses: actions/download-artifact@v2
#       with:
#         name: web-release

#     - name: Deploy to gh-pages
#       uses: peaceiris/actions-gh-pages@v3
#       with:
#         github_token: ${{ secrets.GITHUB_TOKEN }}
#         publish_dir: ./build/web