name: GitHub Pages Release

on:
  push:
    branches:
      - master

  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    #permissions:
      #contents: write
    steps:
        - uses: actions/checkout@v3

        - name: Setup Flutter
          run: |
            git clone https://github.com/flutter/flutter.git --depth 1 -b beta _flutter
            echo "${GITHUB_WORKSPACE}/_flutter/bin" >> ${GITHUB_PATH}
  
        - name: Install
          run: |
            flutter config --enable-web
            flutter pub get
  
        - name: Build
          run: flutter build web --release
  
        - name: Deploy
          uses: peaceiris/actions-gh-pages@v3
          if: ${{ github.ref == 'refs/heads/master' }}
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./build/web


# jobs:
#   build:
#     name: Create Web Build
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - uses: actions/setup-java@v3
#         with:
#           distribution: 'zulu'
#           java-version: "12.x"
#           cache: gradle
#       - uses: subosito/flutter-action@v2
#         with:
#           flutter-version: "3.0.0"
#           channel: 'stable'
#           cache: true
      
#       - name: Get dependencies
#         run: flutter pub get

#       - name: Start Web Release Build
#         run: flutter build web --release
     
#       - name: Upload Web Build Files
#         uses: actions/upload-artifact@v2
#         with:
#           name: web-release
#           path: ./build/web

#   deploy:
#     name: Deploy Web Build
#     needs: build
#     runs-on: ubuntu-latest

#     steps:
#     - name: Download Web Release
#       uses: actions/download-artifact@v2
#       with:
#         name: web-release

#     - name: Deploy to gh-pages
#       uses: peaceiris/actions-gh-pages@v3
#       with:
#         github_token: ${{ secrets.GITHUB_TOKEN }}
#         publish_dir: ./build/web